services:
  keycloak:
    image: quay.io/keycloak/keycloak
    command: start-dev
    ports:
      - "8080:8080"
    environment:
      KC_DB: dev-mem
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin